In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('C:\\Users\\91950\\OneDrive\\Desktop\\online_food_delivery_dataset.csv')

In [4]:
df.head()

,Order_ID,Order_Date,City,Restaurant_Name,Cuisine_Type,Order_Amount,Discount_Applied,Discount_Amount,Final_Amount,Payment_Method,Delivery_Time_Minutes,Distance_km,Rider_Rating,Customer_Rating,Order_Status
0,ORD1,22-02-2026,Mumbai,Spice Hub,Italian,842.90,Yes,0.0,842.90,Card,107,6.32,4.4,3.8,Delivered
1,ORD2,22-02-2026,Pune,Curry Kingdom,Indian,974.79,Yes,50.0,924.79,UPI,101,2.68,4.7,3.8,Cancelled
2,ORD3,22-02-2026,Hyderabad,Sushi Spot,Chinese,1459.93,NaN,0.0,1459.93,Card,36,2.64,4.3,4.8,Cancelled
3,ORD4,22-02-2026,Chennai,Sushi Spot,Italian,151.44,Yes,100.0,51.44,Cash,74,6.32,3.3,3.6,Delivered
4,ORD5,22-02-2026,Delhi,Burger Town,Indian,949.10,Yes,0.0,949.10,Card,63,16.22,3.5,2.1,Delayed

# DATA EXPLORATION

In [5]:
df.shape

(2000, 15)

In [6]:
df.dtypes

Order_ID                  object
Order_Date                object
City                      object
Restaurant_Name           object
Cuisine_Type              object
Order_Amount             float64
Discount_Applied          object
Discount_Amount          float64
Final_Amount             float64
Payment_Method            object
Delivery_Time_Minutes      int64
Distance_km              float64
Rider_Rating             float64
Customer_Rating          float64
Order_Status              object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               2000 non-null   object
 1   Order_Date             2000 non-null   object
 2   City                   2000 non-null   object
 3   Restaurant_Name        2000 non-null   object
 4   Cuisine_Type           2000 non-null   object
 5   Order_Amount           2000 non-null   float64
 6   Discount_Applied       1308 non-null   object
 7   Discount_Amount        1602 non-null   float64
 8   Final_Amount           2000 non-null   float64
 9   Payment_Method         2000 non-null   object
 10  Delivery_Time_Minutes  2000 non-null   int64
 11  Distance_km            2000 non-null   float64
 12  Rider_Rating           2000 non-null   float64
 13  Customer_Rating        2000 non-null   float64
 14  Order_Status           2000 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 234.5+ KB

# DATA CLEANING

In [8]:
df.isnull().sum()

Order_ID                   0
Order_Date                 0
City                       0
Restaurant_Name            0
Cuisine_Type               0
Order_Amount               0
Discount_Applied         692
Discount_Amount          398
Final_Amount               0
Payment_Method             0
Delivery_Time_Minutes      0
Distance_km                0
Rider_Rating               0
Customer_Rating            0
Order_Status               0
dtype: int64

In [9]:
df["Discount_Applied"]=df["Discount_Applied"].fillna(df["Discount_Applied"].mode()[0])

In [10]:
df.isnull().sum()

Order_ID                   0
Order_Date                 0
City                       0
Restaurant_Name            0
Cuisine_Type               0
Order_Amount               0
Discount_Applied           0
Discount_Amount          398
Final_Amount               0
Payment_Method             0
Delivery_Time_Minutes      0
Distance_km                0
Rider_Rating               0
Customer_Rating            0
Order_Status               0
dtype: int64

In [11]:
print(df["Discount_Amount"].skew())

0.03352813227963141

In [12]:
df["Discount_Amount"]=df["Discount_Amount"].fillna(df["Discount_Amount"].mean())

In [13]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
City                     0
Restaurant_Name          0
Cuisine_Type             0
Order_Amount             0
Discount_Applied         0
Discount_Amount          0
Final_Amount             0
Payment_Method           0
Delivery_Time_Minutes    0
Distance_km              0
Rider_Rating             0
Customer_Rating          0
Order_Status             0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

# Outliers Analysis

In [15]:
import numpy as np

In [16]:
numeric_data=df.select_dtypes(include=np.number)

In [17]:
for i in numeric_data:
    q1=numeric_data[i].quantile(0.25)
    q2=numeric_data[i].quantile(0.50)
    q3=numeric_data[i].quantile(0.75)

In [18]:
IQR=q3-q1

In [19]:
Uw=q3+1.5*IQR
Lw=q1-1.5*IQR

In [20]:
Outliers=((numeric_data[i]>Uw)|(numeric_data[i]<Lw))

In [21]:
print(Outliers.sum())

0

# DATA ANALYSIS

In [22]:
df.head()

,Order_ID,Order_Date,City,Restaurant_Name,Cuisine_Type,Order_Amount,Discount_Applied,Discount_Amount,Final_Amount,Payment_Method,Delivery_Time_Minutes,Distance_km,Rider_Rating,Customer_Rating,Order_Status
0,ORD1,22-02-2026,Mumbai,Spice Hub,Italian,842.90,Yes,0.0,842.90,Card,107,6.32,4.4,3.8,Delivered
1,ORD2,22-02-2026,Pune,Curry Kingdom,Indian,974.79,Yes,50.0,924.79,UPI,101,2.68,4.7,3.8,Cancelled
2,ORD3,22-02-2026,Hyderabad,Sushi Spot,Chinese,1459.93,Yes,0.0,1459.93,Card,36,2.64,4.3,4.8,Cancelled
3,ORD4,22-02-2026,Chennai,Sushi Spot,Italian,151.44,Yes,100.0,51.44,Cash,74,6.32,3.3,3.6,Delivered
4,ORD5,22-02-2026,Delhi,Burger Town,Indian,949.10,Yes,0.0,949.10,Card,63,16.22,3.5,2.1,Delayed

In [62]:
df["Distance_Type"]=pd.cut(df["Distance_km"],bins=[0,8,16,32],labels=["Short_dist","Mid_dist","Long_dist"])

In [65]:
s=df

In [66]:
s

,Order_ID,Order_Date,City,Restaurant_Name,Cuisine_Type,Order_Amount,Discount_Applied,Discount_Amount,Final_Amount,Payment_Method,Delivery_Time_Minutes,Distance_km,Rider_Rating,Customer_Rating,Order_Status,Distance_Type
0,ORD1,22-02-2026,Mumbai,Spice Hub,Italian,842.90,Yes,0.0,842.90,Card,107,6.32,4.4,3.8,Delivered,Short_dist
1,ORD2,22-02-2026,Pune,Curry Kingdom,Indian,974.79,Yes,50.0,924.79,UPI,101,2.68,4.7,3.8,Cancelled,Short_dist
2,ORD3,22-02-2026,Hyderabad,Sushi Spot,Chinese,1459.93,NaN,0.0,1459.93,Card,36,2.64,4.3,4.8,Cancelled,Short_dist
3,ORD4,22-02-2026,Chennai,Sushi Spot,Italian,151.44,Yes,100.0,51.44,Cash,74,6.32,3.3,3.6,Delivered,Short_dist
4,ORD5,22-02-2026,Delhi,Burger Town,Indian,949.10,Yes,0.0,949.10,Card,63,16.22,3.5,2.1,Delayed,Long_dist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD1996,22-02-2026,Bangalore,Biryani House,Indian,944.25,NaN,NaN,944.25,Card,45,5.85,3.0,4.0,Delivered,Short_dist
1996,ORD1997,22-02-2026,Delhi,Curry Kingdom,Fast Food,1000.04,Yes,NaN,1000.04,Cash,27,1.00,4.9,4.4,Delayed,Short_dist
1997,ORD1998,22-02-2026,Chennai,Burger Town,Italian,1822.37,Yes,100.0,1722.37,Card,114,17.08,4.6,3.4,Delayed,Long_dist
1998,ORD1999,22-02-2026,Bangalore,Pizza Palace,Fast Food,531.14,NaN,0.0,531.14,Wallet,26,16.60,2.9,3.5,Delayed,Long_dist
1999,ORD2000,22-02-2026,Delhi,Sushi Spot,Fast Food,914.43,Yes,50.0,864.43,Wallet,29,13.85,4.0,3.4,Delayed,Mid_dist

In [35]:
a=pd.DataFrame(df.groupby("Cuisine_Type")["Order_ID"].count().sort_values(ascending=False))
a.to_csv("Popular_Cuisine")

In [26]:
b=pd.DataFrame(df.groupby("Restaurant_Name")["Customer_Rating"].mean().sort_values(ascending=False))
b.to_csv("Restaurant_Rating")

In [27]:
c=pd.DataFrame(df.groupby("Payment_Method")["Final_Amount"].mean().sort_values(ascending=False))
c.to_csv("Payment_Method_Amount")

In [28]:
d=pd.DataFrame(df.groupby("Restaurant_Name")["Order_ID"].count().sort_values(ascending=False))
d.to_csv("Restaurant_Orders")

In [30]:
e=pd.DataFrame(df.groupby("Payment_Method")["Order_ID"].count().sort_values(ascending=False))
e.to_csv("Payment_Type")

In [31]:
f=pd.DataFrame(df.groupby("Order_Status")["Order_ID"].count().sort_values(ascending=False))
f.to_csv("Order_Status")

In [33]:
g=pd.DataFrame(df.groupby("City")["Final_Amount"].mean().sort_values(ascending=False))
g.to_csv("City_Wise_Revenue")

In [49]:
# Count orders by Distance Type and Order Status
cancel_rate = pd.crosstab(
    df["Distance_Type"],
    df["Order_Status"],
    normalize="index"
) * 100
cancel_rate.to_csv("Cancellation_Rate_By_Distance.csv")
cancel_rate

Order_Status   Cancelled    Delayed  Delivered
Distance_Type
Short_dist     36.363636  33.403805  30.232558
Mid_dist       32.633588  31.870229  35.496183
Long_dist      33.100698  33.399801  33.499501

In [54]:
h=pd.DataFrame(df)
h.to_csv("Table_OFD")

In [67]:
j=pd.DataFrame(s)
j.to_csv("Table_OFD2")

In [60]:
import os

In [61]:
os.getcwd()

'C:\\Users\\91950'